### ISSUE TITLE
Should reprompt user about what to do to database if they don't enter y or n

### ISSUE THREAD

**Issue by CuriousG102** [texastribune/tx_salaries#103]
https://github.com/texastribune/tx_salaries/blob/5f85ca7c32d6a71d90dc65c85ef11c4a4de2e782/tx_salaries/management/commands/import_salary_data.py#L86-L98

Could be done with a while loop. Basically I think a typo (I hit "u" and enter) could cause problems with the current code

**Comment by rdmurphy** [comment]
Yeah. Good point. We should make that change.

**Comment by CuriousG102** [comment]
I'll make a PR

**Comment by CuriousG102** [comment]
https://github.com/texastribune/tx_salaries/pull/104
